-- Write a PL/SQL block to calculate the square and cube of the given number.

DECLARE
 NUMERIC_VALUE NUMBER(8):= 5;
 SQUARE NUMBER;
 CUBE NUMBER;
BEGIN
 SQUARE:= NUMERIC_VALUE*NUMERIC_VALUE;
 CUBE:=  NUMERIC_VALUE*NUMERIC_VALUE*NUMERIC_VALUE;
 DBMS_OUTPUT.PUT_LINE('GIVEN NUMERICAL VALUE = ' || NUMERIC_VALUE);
 DBMS_OUTPUT.PUT_LINE('SQUARE = ' || SQUARE);
 DBMS_OUTPUT.PUT_LINE('CUBE = ' || CUBE);
END;
/