-- 3) Write a PL/SQL block to accept product name, qty and price from user and then calculate discount in Rs. based on the given (%).

SET SERVEROUTPUT ON;
DECLARE
    PRODUCT_NAME VARCHAR2(50);
    QUANTITY NUMBER;
    PRICE NUMBER;
    DISCOUNT_PERCENTAGE NUMBER;
    TOTAL_AMOUNT NUMBER;
    DISCOUNT_AMOUNT NUMBER;
    FINAL_AMOUNT NUMBER;
BEGIN
    PRODUCT_NAME := '&ENTER_PRODUCT_NAME';
    QUANTITY := &ENTER_QUANTITY;
    PRICE := &ENTER_PRICE;
    DISCOUNT_PERCENTAGE := &ENTER_DISCOUNT_PERCENTAGE;
    TOTAL_AMOUNT := QUANTITY * PRICE;
    DISCOUNT_AMOUNT := (TOTAL_AMOUNT * DISCOUNT_PERCENTAGE) / 100;
    FINAL_AMOUNT := TOTAL_AMOUNT - DISCOUNT_AMOUNT;
    DBMS_OUTPUT.PUT_LINE('PRODUCT NAME : ' || PRODUCT_NAME);
    DBMS_OUTPUT.PUT_LINE('QUANTITY : ' || QUANTITY);
    DBMS_OUTPUT.PUT_LINE('PRICE : ' || PRICE);
    DBMS_OUTPUT.PUT_LINE('TOTAL AMOUNT : ' || TOTAL_AMOUNT);
    DBMS_OUTPUT.PUT_LINE('DISCOUNT RS. : ' || DISCOUNT_AMOUNT);
    DBMS_OUTPUT.PUT_LINE('FINAL AMOUNT : ' || FINAL_AMOUNT);
END;
/